AllCops:
  TargetRubyVersion: 3.1
  DisplayCopNames: true
  UseCache: true
  SuggestExtensions: false
  NewCops: enable

Layout/LineLength:
  Max: 152

Metrics/BlockLength:
  Exclude:
    - Gemfile
    - net_suite.gemspec

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
