version: 2.1
jobs:
  build:
    docker:
      - image: ruby:3.1.2
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install bundler -v 2.3.19
            bundle install
          when: always
      - run:
          name: Rubocop
          command: bundle exec rubocop
          when: always
      - run:
          name: Run specs
          command: bundle exec rake
          when: always
